"""Initial tables

Revision ID: 73f963675171
Revises: cad30b539cbf
Create Date: 2025-12-01 15:20:07.177845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73f963675171'
down_revision = 'cad30b539cbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###